-- Split out of drizzle-kit's generated 0000_app_tables.sql output (policy
-- statements only) so it can apply after 0001_private_rls_helpers.sql,
-- whose functions these policies reference.
CREATE POLICY "uploader and tenant staff can select application documents" ON "app"."application_documents" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("app"."application_documents"."uploaded_by" = (select auth.uid()) or (select private.can_view_org("app"."application_documents"."organization_id")));--> statement-breakpoint
CREATE POLICY "uploader can insert application documents" ON "app"."application_documents" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("app"."application_documents"."uploaded_by" = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "staff can update application document status" ON "app"."application_documents" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select private.is_hoc_staff())) WITH CHECK ((select private.is_hoc_staff()));--> statement-breakpoint
CREATE POLICY "staff see all notes, tenant sees non-internal notes" ON "app"."application_notes" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select private.is_hoc_staff()) or (not "app"."application_notes"."internal" and (select private.can_view_org("app"."application_notes"."organization_id"))));--> statement-breakpoint
CREATE POLICY "staff can insert notes" ON "app"."application_notes" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select private.is_hoc_staff()));--> statement-breakpoint
CREATE POLICY "applicants and tenant staff can select applications" ON "app"."applications" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("app"."applications"."applicant_user_id" = (select auth.uid()) or (select private.can_view_org("app"."applications"."organization_id")));--> statement-breakpoint
CREATE POLICY "applicants can insert own applications" ON "app"."applications" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("app"."applications"."applicant_user_id" = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "applicants can update own draft applications" ON "app"."applications" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (("app"."applications"."applicant_user_id" = (select auth.uid()) and "app"."applications"."status" = 'draft') or (select private.is_hoc_staff())) WITH CHECK (("app"."applications"."applicant_user_id" = (select auth.uid()) and "app"."applications"."status" in ('draft', 'submitted')) or (select private.is_hoc_staff()));--> statement-breakpoint
CREATE POLICY "individuals can select own platform role" ON "app"."platform_roles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("app"."platform_roles"."user_id" = (select auth.uid()) or (select private.is_hoc_staff()));--> statement-breakpoint
CREATE POLICY "individuals can select own profile" ON "app"."profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("app"."profiles"."id" = (select auth.uid()) or (select private.is_hoc_staff()));--> statement-breakpoint
CREATE POLICY "individuals can update own profile" ON "app"."profiles" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("app"."profiles"."id" = (select auth.uid())) WITH CHECK ("app"."profiles"."id" = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "members can select own membership rows" ON "app"."organization_memberships" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("app"."organization_memberships"."user_id" = (select auth.uid()) or (select private.can_view_org("app"."organization_memberships"."organization_id")));--> statement-breakpoint
CREATE POLICY "owners and staff manage memberships" ON "app"."organization_memberships" AS PERMISSIVE FOR ALL TO "authenticated" USING ((select private.is_hoc_staff()) or (select private.has_org_role("app"."organization_memberships"."organization_id", array['owner']::text[]))) WITH CHECK ((select private.is_hoc_staff()) or (select private.has_org_role("app"."organization_memberships"."organization_id", array['owner']::text[])));--> statement-breakpoint
CREATE POLICY "creator and tenant can select organizations" ON "app"."organizations" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("app"."organizations"."created_by" = (select auth.uid()) or (select private.can_view_org("app"."organizations"."id")));--> statement-breakpoint
CREATE POLICY "individuals can insert own organizations" ON "app"."organizations" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("app"."organizations"."created_by" = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "owners and staff can update organizations" ON "app"."organizations" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select private.is_hoc_staff()) or (select private.has_org_role("app"."organizations"."id", array['owner']::text[]))) WITH CHECK ((select private.is_hoc_staff()) or (select private.has_org_role("app"."organizations"."id", array['owner']::text[])));