-- Milestone 9: operations domain tables (trips, trip_events, telemetry,
-- charging, maintenance) + additive dispatch columns on drivers. Generated by
-- drizzle-kit, then hand-split: policies live in 0021, grants in 0022. The
-- gis.geography(Point,4326) type is written unquoted (drizzle emits it quoted,
-- which Postgres would read as a single identifier and reject). Requires 0019.
CREATE TYPE "app"."charging_status" AS ENUM('in_progress', 'completed');--> statement-breakpoint
CREATE TYPE "app"."driver_operational_status" AS ENUM('offline', 'available', 'on_trip');--> statement-breakpoint
CREATE TYPE "app"."maintenance_severity" AS ENUM('low', 'medium', 'high', 'critical');--> statement-breakpoint
CREATE TYPE "app"."maintenance_status" AS ENUM('open', 'in_progress', 'resolved');--> statement-breakpoint
CREATE TYPE "app"."trip_source" AS ENUM('manual', 'corporate', 'api', 'rider_future');--> statement-breakpoint
CREATE TYPE "app"."trip_status" AS ENUM('requested', 'offered', 'assigned', 'driver_en_route', 'driver_arrived', 'in_progress', 'completed', 'cancelled');--> statement-breakpoint
CREATE TYPE "app"."vehicle_health_state" AS ENUM('nominal', 'attention', 'critical');--> statement-breakpoint
CREATE TABLE "app"."charging_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"driver_id" uuid,
	"location_label" text,
	"status" "app"."charging_status" DEFAULT 'in_progress' NOT NULL,
	"energy_wh" integer,
	"cost_minor" bigint,
	"currency" text,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ended_at" timestamp with time zone,
	"created_by_user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "charging_energy_nonnegative" CHECK ("app"."charging_sessions"."energy_wh" is null or "app"."charging_sessions"."energy_wh" >= 0),
	CONSTRAINT "charging_cost_nonnegative" CHECK ("app"."charging_sessions"."cost_minor" is null or "app"."charging_sessions"."cost_minor" >= 0),
	CONSTRAINT "charging_currency_format" CHECK ("app"."charging_sessions"."currency" is null or char_length("app"."charging_sessions"."currency") = 3),
	CONSTRAINT "charging_cost_requires_currency" CHECK ("app"."charging_sessions"."cost_minor" is null or "app"."charging_sessions"."currency" is not null),
	CONSTRAINT "charging_ended_after_started" CHECK ("app"."charging_sessions"."ended_at" is null or "app"."charging_sessions"."ended_at" > "app"."charging_sessions"."started_at")
);
--> statement-breakpoint
ALTER TABLE "app"."charging_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."maintenance_tickets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"category" text NOT NULL,
	"severity" "app"."maintenance_severity" DEFAULT 'medium' NOT NULL,
	"status" "app"."maintenance_status" DEFAULT 'open' NOT NULL,
	"title" text NOT NULL,
	"notes" text,
	"opened_by_user_id" uuid NOT NULL,
	"opened_at" timestamp with time zone DEFAULT now() NOT NULL,
	"resolved_by_user_id" uuid,
	"resolved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "maintenance_title_not_blank" CHECK (char_length(btrim("app"."maintenance_tickets"."title")) > 0)
);
--> statement-breakpoint
ALTER TABLE "app"."maintenance_tickets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."trip_events" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "app"."trip_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" uuid NOT NULL,
	"trip_id" uuid NOT NULL,
	"event_type" text NOT NULL,
	"from_status" "app"."trip_status",
	"to_status" "app"."trip_status",
	"actor_user_id" uuid,
	"payload" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."trip_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."trips" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"vehicle_id" uuid,
	"driver_id" uuid,
	"source" "app"."trip_source" DEFAULT 'manual' NOT NULL,
	"rider_ref" text,
	"pickup_label" text NOT NULL,
	"pickup" gis.geography(Point,4326) NOT NULL,
	"dropoff_label" text NOT NULL,
	"dropoff" gis.geography(Point,4326) NOT NULL,
	"status" "app"."trip_status" DEFAULT 'requested' NOT NULL,
	"distance_meters" integer,
	"energy_wh" integer,
	"fare_minor" bigint,
	"currency" text,
	"requested_at" timestamp with time zone DEFAULT now() NOT NULL,
	"assigned_at" timestamp with time zone,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"cancelled_at" timestamp with time zone,
	"created_by_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "trips_fare_nonnegative" CHECK ("app"."trips"."fare_minor" is null or "app"."trips"."fare_minor" >= 0),
	CONSTRAINT "trips_distance_nonnegative" CHECK ("app"."trips"."distance_meters" is null or "app"."trips"."distance_meters" >= 0),
	CONSTRAINT "trips_energy_nonnegative" CHECK ("app"."trips"."energy_wh" is null or "app"."trips"."energy_wh" >= 0),
	CONSTRAINT "trips_currency_format" CHECK ("app"."trips"."currency" is null or char_length("app"."trips"."currency") = 3),
	CONSTRAINT "trips_fare_requires_currency" CHECK ("app"."trips"."fare_minor" is null or "app"."trips"."currency" is not null)
);
--> statement-breakpoint
ALTER TABLE "app"."trips" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "app"."vehicle_telemetry_snapshots" (
	"vehicle_id" uuid PRIMARY KEY NOT NULL,
	"organization_id" uuid NOT NULL,
	"location" gis.geography(Point,4326),
	"state_of_charge_pct" integer,
	"odometer_km" integer,
	"health_state" "app"."vehicle_health_state",
	"source" text DEFAULT 'demo' NOT NULL,
	"observed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "telemetry_soc_range" CHECK ("app"."vehicle_telemetry_snapshots"."state_of_charge_pct" is null or ("app"."vehicle_telemetry_snapshots"."state_of_charge_pct" between 0 and 100)),
	CONSTRAINT "telemetry_odometer_nonnegative" CHECK ("app"."vehicle_telemetry_snapshots"."odometer_km" is null or "app"."vehicle_telemetry_snapshots"."odometer_km" >= 0)
);
--> statement-breakpoint
ALTER TABLE "app"."vehicle_telemetry_snapshots" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "app"."drivers" ADD COLUMN "operational_status" "app"."driver_operational_status" DEFAULT 'offline' NOT NULL;--> statement-breakpoint
ALTER TABLE "app"."drivers" ADD COLUMN "current_location" gis.geography(Point,4326);--> statement-breakpoint
ALTER TABLE "app"."drivers" ADD COLUMN "last_seen_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "app"."charging_sessions" ADD CONSTRAINT "charging_sessions_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "app"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."charging_sessions" ADD CONSTRAINT "charging_sessions_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "app"."vehicles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."charging_sessions" ADD CONSTRAINT "charging_sessions_driver_id_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "app"."drivers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."charging_sessions" ADD CONSTRAINT "charging_sessions_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."maintenance_tickets" ADD CONSTRAINT "maintenance_tickets_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "app"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."maintenance_tickets" ADD CONSTRAINT "maintenance_tickets_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "app"."vehicles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."maintenance_tickets" ADD CONSTRAINT "maintenance_tickets_opened_by_user_id_users_id_fk" FOREIGN KEY ("opened_by_user_id") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."maintenance_tickets" ADD CONSTRAINT "maintenance_tickets_resolved_by_user_id_users_id_fk" FOREIGN KEY ("resolved_by_user_id") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."trip_events" ADD CONSTRAINT "trip_events_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "app"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."trip_events" ADD CONSTRAINT "trip_events_trip_id_trips_id_fk" FOREIGN KEY ("trip_id") REFERENCES "app"."trips"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."trip_events" ADD CONSTRAINT "trip_events_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."trips" ADD CONSTRAINT "trips_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "app"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."trips" ADD CONSTRAINT "trips_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "app"."vehicles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."trips" ADD CONSTRAINT "trips_driver_id_drivers_id_fk" FOREIGN KEY ("driver_id") REFERENCES "app"."drivers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."trips" ADD CONSTRAINT "trips_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."vehicle_telemetry_snapshots" ADD CONSTRAINT "vehicle_telemetry_snapshots_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "app"."vehicles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."vehicle_telemetry_snapshots" ADD CONSTRAINT "vehicle_telemetry_snapshots_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "app"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "charging_org_idx" ON "app"."charging_sessions" USING btree ("organization_id","started_at");--> statement-breakpoint
CREATE INDEX "charging_vehicle_idx" ON "app"."charging_sessions" USING btree ("vehicle_id");--> statement-breakpoint
CREATE INDEX "maintenance_org_status_idx" ON "app"."maintenance_tickets" USING btree ("organization_id","status");--> statement-breakpoint
CREATE INDEX "maintenance_vehicle_idx" ON "app"."maintenance_tickets" USING btree ("vehicle_id");--> statement-breakpoint
CREATE INDEX "trip_events_trip_idx" ON "app"."trip_events" USING btree ("trip_id","created_at");--> statement-breakpoint
CREATE INDEX "trip_events_org_idx" ON "app"."trip_events" USING btree ("organization_id","created_at");--> statement-breakpoint
CREATE INDEX "trips_org_status_requested_idx" ON "app"."trips" USING btree ("organization_id","status","requested_at");--> statement-breakpoint
CREATE INDEX "trips_driver_status_idx" ON "app"."trips" USING btree ("driver_id","status");--> statement-breakpoint
CREATE INDEX "trips_pickup_gist" ON "app"."trips" USING gist ("pickup");--> statement-breakpoint
CREATE INDEX "trips_dropoff_gist" ON "app"."trips" USING gist ("dropoff");--> statement-breakpoint
CREATE INDEX "telemetry_org_idx" ON "app"."vehicle_telemetry_snapshots" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "telemetry_location_gist" ON "app"."vehicle_telemetry_snapshots" USING gist ("location");--> statement-breakpoint
CREATE INDEX "drivers_available_location_gist" ON "app"."drivers" USING gist ("current_location") WHERE "app"."drivers"."operational_status" = 'available' and "app"."drivers"."current_location" is not null;
